apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    type: proxy
spec:
  containers:
  - name: nginx
    image: nginx:1.26
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
