apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.26
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    env:
    - name: TEST_ENV
      value: "333"
    # command: ["/bin/bash", "-c"] # It overrides the initialization of NGINX
    # args: ["echo ${TEST_ENV}"] # Use `kubectl logs nginx` to see the output
    command: ["nginx"]
    args: ["-g", "daemon off;"]

