apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helloworld.fullname" . }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helloworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helloworld.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 5 # Added configuration 
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helloworld.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: # Added configuration
          - sh
          - -c
          # >> This line needs to be commented out of the template because its incorrect.
          {{/* "echo 1234 > {{ .Values.volumeMounts[0].mountPath }}/file; sleep 3600" */}} # Incorrect
          # >> This line doesn't need to be removed because the template syntax is correct.
          # - "echo 1234 > {{ index .Values.volumeMounts 0 "mountPath" }}/file; sleep 3600" # Correct
          - "echo 1234 > {{ (index .Values.volumeMounts 0).mountPath }}/file; sleep 3600" # Also correct

          # ports:
          #   - name: http
          #     containerPort: {{ .Values.service.port }}
          #     protocol: TCP

          # livenessProbe:
          {{/*  {{- toYaml .Values.livenessProbe | nindent 12 }} */}}
          # readinessProbe:
          {{/*  {{- toYaml .Values.readinessProbe | nindent 12 }} */}}
          # resources:
          {{/*  {{- toYaml .Values.resources | nindent 12 }} */}}
          
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }} # This line will paste here all attributes present in .Values.volumeMounts
          {{- end }}
          
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
