---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "helloworld.fullname" . }}-pre-install-job-hook"
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: pre-install
        image: busybox:stable-uclibc
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - "echo pre-install Job is running; sleep 10"
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
  backoffLimit: 3
  completions: 1
  parallelism: 1
