apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: busybox
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: busybox
    image: busybox:stable-uclibc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /var/www
      name: volsecret
  volumes:
  - name: volsecret
    secret:
      secretName: opaque-secret

# kubectl exec -it busybox2 -- sh -c "cd /var/www && sh"