# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devinc-sa
  namespace: devinc
# When set to false, you will need to manually provide a token for the ServiceAccount.
automountServiceAccountToken: true
---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-role
  namespace: devinc
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-role-binding
  namespace: devinc
subjects:
- kind: ServiceAccount
  name: devinc-sa
  # apiGroup: rbac.authorization.k8s.io # Unsuported
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io