apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: devinc
  labels:
    app: nginx
spec:
  serviceAccountName: devinc-sa
  containers:
  - name: nginx
    image: nginx:1.26
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80

# kubectl exec -it -n devinc nginx -- bash