apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  selector:
    app: spring-hello-v1
    # app: spring-hello-v2
  ports:
  - port: 4000
    targetPort: 8080

# kubectl apply -f service.yml
# kubectl delete -f service.yml
# kubectl port-forward service/spring-svc 80:4000