apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dpl-v2
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: spring-hello-v2
  template:
    metadata:
      labels:
        app: spring-hello-v2
    spec:
      containers:
      - name: spring-hello-v2
        image: albertalvin/k8s-spring-hello:0.0.6-SNAPSHOT
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

# kubectl apply -f spring-hello-v2.yml
# kubectl delete -f spring-hello-v2.yml