apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.36-debian
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: db_test
        volumeMounts:
        - name: db-init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-init-script
          configMap: 
            name: init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

# kubectl create configmap init-sql --from-file=.\spring\init.sql
# kubectl get configmap
# kubectl apply -f mysql.yml
# kubectl delete -f mysql.yml