apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: no-access
  namespace: devinc
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: no-access-binding
  namespace: devinc
subjects:
- kind: User
  name: "Albert Alvin" # Same name as in the certificate's CN, not as in the kubeconfig file.
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: no-access
  apiGroup: rbac.authorization.k8s.io
