# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: spring-hello
  template:
    metadata:
      labels:
        app: spring-hello
    spec:
      containers:
      - name: spring-hello
        image: albertalvin/k8s-spring-hello:0.0.6-SNAPSHOT
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: spring-hello
spec:
  type: LoadBalancer
  selector:
    app: spring-hello
  ports:
  - port: 2000
    targetPort: 8080
