apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    type: proxy
spec:
  replicas: 3
  selector:
    matchLabels: # needs to match 
      app: nginx
      type: proxy
  template:
    metadata:
      labels: # needs to match (may omit labels, but cannot use different ones)
        app: nginx
        type: proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.26
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
          - containerPort: 80

# kubectl apply -f nginx-rs.yml
# kubectl delete -f nginx-rs.yml
# kubectl get rs
# kubectl describe rs nginx-rs