apiVersion: v1
kind: Pod
metadata:
  name: private-pod
  labels:
    app: private
spec:
  containers:
  - name: private
    image: albertalvin/k8s-spring-hello:0.0.6-SNAPSHOT
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  imagePullSecrets:
  - name: dockercfg-secret
---