apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.26
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # This init-container is copying an index.html to a volume which will then be used by NGINX.
  initContainers:
  - name: init-service
    image: debian:trixie-20240513-slim
    command: 
    - apt-get update
    - apt-get install wget -y
    - wget -O /work-dir/index.html http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: /work-dir
  volumes:
  - name: workdir
    emptyDir: {}
