apiVersion: v1
kind: Pod
metadata:
  name: debian
  labels:
    name: debian
spec:
  containers:
  - name: debian
    image: debian:trixie-20240513-slim
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    # ports:
      # - containerPort: <Port>
    command:
    - /bin/bash
    - -c
    - while true; do sleep 10; done; # May exceed the grace-period and get killed. 
    # - tail -f /dev/null # Same here
    
# kubectl exec -it debian -- bash