---
repositories:
  - name: spring-repo
    url: git+https://github.com/albertalvin8080/Learning-Kubernetes@25-helm/25-02-k8s-spring-hello?ref=main&sparse=0

  - name: hello-repo
    url: git+https://github.com/albertalvin8080/Learning-Kubernetes@25-helm/25-01-helloworld?ref=main&sparse=0
releases:
  - name: spring
    namespace: spring-ns
    chart: spring-repo/k8sspringhello
    version: 0.1.0 # Refers to a property inside 'k8sspringhello/Chart.yaml'
    installed: true

  - name: helloworld
    namespace: default
    chart: hello-repo/helloworld
    version: 0.1.0
    installed: true
