apiVersion: v1
kind: Pod
metadata:
  name: private-pod
  labels:
    app: private
spec:
  containers:
  - name: private
    image: albertalvin/k8s-spring-private-hello:eclipse-temurin
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  imagePullSecrets:
  - name: dockerconfigjson-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  selector:
    app: private
  ports:
  - port: 3000
    targetPort: 8080

# kubectl describe pod private-pod
# kubectl exec -it private-pod -- bash
# wget -qO- localhost:8080; echo

# kubectl port-forward svc/mysvc 8080:3000