apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: busybox
    image: busybox:stable-uclibc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep", "3600"]
    # ports:
      # - containerPort: <Port>

# kubectl exec -it busybox-pod -- sh
