apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP

# wget -qO- http://clusterip-svc:3000