apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dpl
spec:
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: albertalvin/k8s-spring-hello:0.0.6-SNAPSHOT
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  selector:
    app: spring
  ports:
  - port: 4000
    targetPort: 8080

# 1. kubectl get pod -n kube-system <<- Checks if the Metrics Server is installed
# 2. curl -L -A "Mozilla/5.0" -o metrics-server.yml https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.1/components.yaml
# 3. Add `--kubelet-insecure-tls` to the Deployment section.
# 4. kubectl apply -f metrics-server.yml

# kubectl apply -f deploy.yml
# kubectl delete -f deploy.yml

