apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc2
spec:
  storageClassName: mysc
  resources:
    requests:
      storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
