apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: busybox-allow-egress
  namespace: frontend
spec:
  podSelector: 
    matchLabels:
      app: busybox
  policyTypes:
  - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            type: backend
      - podSelector:
          matchLabels:
            app: nginx
      # ports:
      #   - protocol: TCP
      #     port: 80

# Explanation: This netpol will allow busybox to communicate with the nginx pod

# kubectl apply -f busybox-allow-egress.yaml
# kubectl delete netpol -n frontend busybox-allow-egress

# kubectl get netpol -n frontend
# kubectl describe netpol -n frontend busybox-allow-egress

