version: '3.8'

#Anchor | Alias 
x-deploy: &deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]

services:
  # docker-compose exec -it nginx bash
  mysql:
    image: mysql:8.0.36-debian
    container_name: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=db_test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    # mem_limit: 512m
    <<: *deploy

  web:
    image: albertalvin/k8s-spring-mysql:0.0.1-SNAPSHOT
    container_name: web
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=mysql
    restart: unless-stopped
    <<: *deploy