apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-tcpsocket.yml
  labels:
    app: nginx
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: nginx
    image: nginx:1.26
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - sh
    - -c
    # The second time nginx is started here is to testify that the readiness probe will stop increasing it's failure count.
    - >
      nginx -g 'daemon on;';
      sleep 15;
      service nginx stop;
      sleep 10;
      nginx -g 'daemon on;';
      sleep 3600;
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      periodSeconds: 3
      failureThreshold: 3
      initialDelaySeconds: 5

# kubectl apply -f readiness-probe-tcpsocket.yml.yml
# kubectl delete -f readiness-probe-tcpsocket.yml.yml

# kubectl describe -f readiness-probe-tcpsocket.yml.yml
# kubectl exec -it readiness-probe-tcpsocket.yml -- sh