apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    type: local
spec:
  # Instead of setting this same property as "" in the PVC (you're currently inside the PV, not the PVC), you could also use the same value for both.
  # storageClassName: slow 
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: "/14-persistentVolume"
  
# kubectl get pv
# kubectl describe pv mypv
# kubectl apply -f pv.yaml